### ISSUE TITLE
Personal details

### ISSUE THREAD

**Issue by shubham-8551** [Arc-i-Tech-PlayArea/My-Profile#13]
- [x] #18
- [x] #17

**Comment by supsshinde** [comment]
Really sorry for this mistek

**Comment by supsshinde** [comment]
Create additional pull request with with correct branches **"13_personaldetails"**

**Comment by ajayg2808** [comment]
@dipikakoli26,
PR #41 for this issue is not accepted/ merged yet still why this issue is closed.
