### ISSUE TITLE
Reach me at!

### ISSUE THREAD

**Issue by shubham-8551** [Arc-i-Tech-PlayArea/My-Profile#14]
- [x] #11 
- [x] #12

**Comment by supsshinde** [comment]
@priyapal2000 and @shubham-8551 this US is completed or not ?
If yes then merge it to the epic.

**Comment by supsshinde** [comment]
@shubham-8551 and @priyapal2000  complete US by today itself

**Comment by shubham-8551** [comment]
Done 

Close by #36 PR

**Comment by supsshinde** [comment]
@shubham-8551,
Why you closed this user-story? PR for it not approved yet.
