### ISSUE TITLE
Profile - Head of resume

### ISSUE THREAD

**Issue by shubham-8551** [Arc-i-Tech-PlayArea/My-Profile#18]

**Comment by dipikakoli26** [comment]
@ajayg2808 sir @ajstyle2410 told me to change status that's why i have changed that.

**Comment by ajstyle2410** [comment]
> @ajstyle2410, PR has not accepted yet, why you changed status of task to **Done**

why  @ajayg2808  Sir?

**Comment by supsshinde** [comment]
@ajstyle2410 if the task 'Head of resume' is completed then mark it as done or closed

**Comment by supsshinde** [comment]
@ajstyle2410 please do it as soon as possible.

**Comment by ajstyle2410** [comment]
ok

**Comment by ajstyle2410** [comment]
issue are closed #19

**Comment by supsshinde** [comment]
ok
